I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script call
    call ch0 from _call_ch0
  File "game/script.rpy", line 16, in script
    play music t2
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/script.rpy", line 16, in <module>
    play music t2
NameError: name 't2' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 8, in script call
    call ch0 from _call_ch0
  File "game/script.rpy", line 16, in script
    play music t2
  File "renpy/ast.py", line 1969, in execute
    self.call("execute")
  File "renpy/ast.py", line 1957, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 16, in <module>
    play music t2
NameError: name 't2' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
DDLC 1.0
Tue May  4 23:35:57 2021
